language: cpp
dist: trusty
compiler:
- clang
- gcc
before_script:
  - mkdir build
  - cd build
  - cmake ..
script: make
os:
- linux
- osx
branches:
  only:
  - master
notifications:
  email: false
addons:
  apt:
    sources:
      - george-edison55 # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
